### ISSUE TITLE
split base classes from f2003.py

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#101]
Generic base classes and exceptions are currently in the fparser2 f2003.py file. It would be better to split these out into their own file. utils.py seems to be a reasonable name.

**Comment by arporter** [comment]
How about a separate module for exceptions? (I think we should do this in PSyclone too.)

**Comment by rupertford** [comment]
Branch is split_f2003_file

**Comment by arporter** [comment]
PR #103 has been merged to master.
