### ISSUE TITLE
Add children method to fparser2

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#105]
At the moment different classes have different names to reach children in the fparser2 AST. This is complicated and the names that are used are not obvious.

The proposed solution is to add a children method to the base class which provides the children of the node as a list irrespective of the type of class.

Whether we add support for more complex tree traversal here as well (or as separate functions/methods) still needs to be decided but #102 already points out that parent info is required and it would be natural to be able to get to root from any node of a tree. This makes three methods which naturally sit within a base class. A node filter, get node option, and integrated walk would also make sense, but I'm getting a bit ahead now.

**Comment by pelson** [comment]
Having a "children of node" method definitely makes sense, but for any given node I believe the general implementation looks like:

```
def children(node):
    # Get the immediate children of the given node.
    children = getattr(node, 'content', None)
    if children is None:
        children = getattr(node, 'items', None)
    return children
``` 

The implementation is coded in multiple locations within https://github.com/stfc/fparser/blob/master/src/fparser/two/utils.py - simply having a ```fparser.two.utils.children``` utility function would allow that to be factored.

FWIW The visitor pattern makes pretty light-work of the graph traversal, and has the benefit of not needing behaviour to be defined on the nodes themselves. I had a fairly involved example of re-writing parts of ``node.tofortran()`` using the visitor pattern in the description of #180. Providing a generic Visitor class would be handy though. Something like the following:

```
class Visitor:
    def __init__(self, program):
        self.visit(program)

    def find_visitor_method(self, node):
        for cls in type(node).mro():
            method = getattr(self, f'visit_{cls.__name__}', None)
            if method:
                break
        return method

    def visit(self, node, **kwargs):
        method = self.find_visitor_method(node)
        print('Visiting {} with {}'.format(type(node).__name__, method.__name__))
        method(node, **kwargs)

    def visit_object(self, node, **kwargs):
        # This is the "fallback"/"generic" implementation that will be
        # called if there are no more specific visitor methods.
        for child in children(node) or []:
            self.visit(child, **kwargs)
```

Application code to "get all name nodes" would then look something like:

```
class NodeMatcher(Visitor):
    def __init__(self, program):
        self.matches = []
        super().__init__(program)

    def visit_Name(self, node):
        self.matches.append(node)
        self.visit_object(node)


visitor = NodeMatcher(program)
print('\n'.join([str(n) for n in visitor.matches]))
```

You could easily imagine embellishing this matcher class, but my point is that the behaviour really doesn't need to live on the node itself for it to be hierarchical and tightly aligned to the types produced by fparser.

**Comment by rupertford** [comment]
This is being taken on by @arporter as part of pr #230

**Comment by rupertford** [comment]
PR #230 has been merged to master. Closing this issue.
