### ISSUE TITLE
Module Procedures in a Fortran type

### ISSUE THREAD

**Issue by hiker** [stfc/fparser#108]
The following code is not parsed and then analyzed correctly with fparser 1:
```
module foo
    type, public :: grid_type
   contains
        procedure :: get_tmask
   end type grid_type
end module foo
```

Reason: The class Type does not contain an attribute "module_procedures".

**Comment by arporter** [comment]
I'm a bit confused about this. We use fparser1 to parse LFRic meta-data which is of the form:

      type, extends(kernel_type) :: testkern_type
         type(arg_type), dimension(5) :: meta_args =    &
              (/ arg_type(gh_real, gh_read),     &
                 arg_type(gh_field,gh_write,w1), &
                 arg_type(gh_field,gh_read, w2), &
                 arg_type(gh_field,gh_read, w2), &
                 arg_type(gh_field,gh_read, w3)  &
               /)
         integer :: iterates_over = cells
       contains
         procedure, nopass :: code => testkern_code
      end type testkern_type

**Comment by arporter** [comment]
I've just had a look and psyclone.parse.KernelProcedure has the `get_procedure()` method:
```python
    def get_procedure(ast, name, modast):
        bname = None
        for statement in ast.content:
            if isinstance(statement, fparser1.statements.SpecificBinding):
                if statement.name == "code" and statement.bname != "":
                    # prototype gungho style
                    bname = statement.bname
                elif statement.name.lower() != "code" \
                        and statement.bname != "":
                    raise ParseError(
                        "Kernel type %s binds to a specific procedure but "
                        "does not use 'code' as the generic name." % name)
                else:
                    # psyclone style
                    bname = statement.name
```
will your fix remove the need to search through the `content` to find the `SpecificBinding`?

**Comment by hiker** [comment]
The difference is the pointer assignment:
```
procedure, nopass :: code => testkern_code
```
If I remove the "=> testkern_code"  (and nopass, not sure if this is related), your code fails as well with:
```
>                                           attributes))
E           AttributeError: AttributeHolder instance has no attribute 'module_procedures', expected attributes: parameters, variables, private_id_list, public_id_list, component_names, variable_names, extends, components, attributes

../parsefortran.py:157: in analyze
    self.block.analyze()
../../common/utils.py:304: in new_func
    func(self)
../block_statements.py:330: in analyze
    stmt.analyze()
../../common/utils.py:304: in new_func
    func(self)
../block_statements.py:435: in analyze
    stmt.analyze()
../../common/utils.py:304: in new_func
    func(self)
../block_statements.py:1326: in analyze
    stmt.analyze()
../../common/utils.py:304: in new_func
    func(self)
../statements.py:750: in analyze
    module_procedures = self.parent.a.module_procedures
```

I don't know the attribute handling enough to judge how/why they are used, what the module_procedure is used for
