### ISSUE TITLE
Raise error for spaces within lexical tokens in fparser2

### ISSUE THREAD

**Issue by TeranIvy** [stfc/fparser#112]
`WORDClsBase` class in `utils.py` is incorrectly reproducing Fortran when there are blank characters within lexical tokens. It ignores the spaces and merges variable names instead of reporting an error, e.g. `final :: a b` returns `FINAL :: ab`. 

This behaviour was valid in older Fortran standards however it is now explicitly forbidden [(section 3.3.1 of N1601.pdf)](https://wg5-fortran.org/N1601-N1650/N1601.pdf): "Blank characters shall not appear within lexical tokens other than in a character context or in a format specification."

**Comment by rupertford** [comment]
I can reproduce this issue and have seen it in another PR (for program names). I'm pretty sure its the Name class that needs changing.

**Comment by rupertford** [comment]
Created branch names_with_spaces

**Comment by arporter** [comment]
#124 has been merged.
