### ISSUE TITLE
fparser2 reports syntax error on line after error

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#116]
When parsing the following Fortran:

    MODULE continuity_a030e_mod
      IMPLICIT NONE
      TYPE, EXTENDS(kernel_type) :: continuity_a030e_type
        TYPE(arg), DIMENSION(10) :: meta_args = (/arg(write, ct, pointwise), <snip/> /)
        INTEGER :: iterates_over = internal_pts
        INTEGER :: index_offset = offset_ne
        CONTAINS
        PROCEDURE, NOPASS :: code => continuity_a030e_code
      END TYPE continuity
  CONTAINS
      SUBROUTINE continuity_a030e_code(ji, jj, ssha, sshn, sshn_u, sshn_v, hu, hv, un, vn, rdt, e12t)

fparser2 says:

    E           fparser.two.Fortran2003.FortranSyntaxError: at line 17
    E           >>>  CONTAINS

whereas the error is actually the fact that the name of the type in the `end type` statement doesn't match with that in the opening `type` statement.

**Comment by rupertford** [comment]
This bug has been fixed in #121. The reported error is now ...

```
rupert@ubuntu:~/proj/fparser/src/fparser$ cat test.f90
MODULE continuity_mod
  IMPLICIT NONE
  TYPE, EXTENDS(kernel_type) :: continuity_a030e_type
    TYPE(arg), DIMENSION(10) :: meta_args = 2
    INTEGER :: iterates_over = internal_pts
    INTEGER :: index_offset = offset_ne
    CONTAINS
    PROCEDURE, NOPASS :: code => continuity_a030e_code
 END TYPE continuity_a030e
end module continuity_mod
rupert@ubuntu:~/proj/fparser/src/fparser$ ./scripts/fparser2.py test.f90 
Syntax error: at line 9
>>> END TYPE continuity_a030e
Expecting name 'continuity_a030e_type'
rupert@ubuntu:~/proj/fparser/src/fparser$ 
```

**Comment by rupertford** [comment]
@arporter. Are you OK with me closing this issue?

**Comment by arporter** [comment]
Of course :-)
