### ISSUE TITLE
Location of draft F2003 spec has moved

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#128]
The current link in the documentation gives a 404. It should now be:

https://j3-fortran.org/doc/year/04/04-007.pdf

**Comment by rupertford** [comment]
I can't find the broken link. If I go to our documentation on read-the-docs and click on any of the links to the standards documents then I get the documents and don't receive 404.
See
https://fparser.readthedocs.io/en/latest/introduction.html
and
https://fparser.readthedocs.io/en/latest/developers_guide.html#fparser2

Could you please point me to the particular error.

**Comment by arporter** [comment]
Weird! I definitely got a picture of a cat hiding under some paper when I tried this before. Of course, it works now. Maybe they were rejigging their site?
