### ISSUE TITLE
fparser falls over if non-utf8 chars encountered

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#132]
Given some Fortran that contains a comment like:

    ! Vertical volume fluxesÊ

fparser will fall over with:

    'utf-8' codec can't decode byte 0xca in position 13362: invalid continuation byte

when it tries to read the file. Since the special character is in a comment this is valid Fortran.

**Comment by arporter** [comment]
The code that falls over is actually just the bit in `common.sourceinfo` that reads the file in order to determine whether it is free-format etc. However, I am so far unable to write a test that demonstrates the problem. Presumably, when I create a file from Python everything gets encoded correctly?

**Comment by rupertford** [comment]
I saw a comment about this recently which said to read in the file using rb as the options i.e. read it in as binary rather than text. No idea if it will help!

**Comment by arporter** [comment]
[bad_char.txt](https://github.com/stfc/fparser/files/2628902/bad_char.txt)

**Comment by arporter** [comment]
@rupertford has kindly agreed to take a look...

**Comment by rupertford** [comment]
Created branch not_utf8

**Comment by rupertford** [comment]
In Python 2 all is OK. In Python 3 I get ...

```
(py3) xed67771@arcgdel01:~/proj/fparser/src/fparser$ scripts/fparser2.py bad_char.f90
Traceback (most recent call last):
  File "scripts/fparser2.py", line 122, in <module>
    main()  # pragma: no cover
  File "scripts/fparser2.py", line 117, in main
    runner(parser, options, args)
  File "scripts/fparser2.py", line 87, in runner
    reader = FortranFileReader(filename)
  File "/home/rupert/Envs/py3/lib/python3.6/site-packages/fparser/common/readfortran.py", line 1413, in __init__
    mode = fparser.common.sourceinfo.get_source_info(file_candidate)
  File "/home/rupert/Envs/py3/lib/python3.6/site-packages/fparser/common/sourceinfo.py", line 311, in get_source_info
    return get_source_info_str(file_object.read())
  File "/home/rupert/Envs/py3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 1383: invalid continuation byte
```

**Comment by rupertford** [comment]
The problem is that the file reader in Python3 will fail if it finds an unknown character (one not specified in the character set) whereas in Python 2 it does not. If I use `codec.open(errors='ignore')` in the two places where open is used in the reader then Python3 works. However Python2 then breaks. I narrowed the Python2 error down to a string replace `string.replace('\xa0', ' ')`. If I change the characters to unicode `string.replace(u'\xa0', u' ')` then Python 2 is also OK.

**Comment by arporter** [comment]
PR #184 has been merged. Closing issue.
