### ISSUE TITLE
fparser 0.0.8 release

### ISSUE THREAD

**Issue by TeranIvy** [stfc/fparser#135]
As discussed in the LFRic Telco today (27/11/2018), it would be good to have new PSyclone and fparser releases in December to support the LFRic performance runs. 

This issue is to plan the cut-off point for the new fparser release. The initial suggestion was to include the changes in PRs #131, #133 and #134 in 0.0.8. After that the relevant developers can continue to test fparser2 on LFRic and UM code.

**Comment by arporter** [comment]
I'm fine with that. Can we call this the "license has passed" release? :-)

**Comment by rupertford** [comment]
Hi @TeranIvy. @arporter and I have just discussed this and we agree that it makes sense to make a new release before going to 1.0 as the changes we would like to make for 1.0 would cause too much delay.

**Comment by rupertford** [comment]
The PR's are now on master so I'll make a release.

**Comment by rupertford** [comment]
Well that was a pain.
As with 0.0.7 the automatic push to pypi failed. Andy says he will fix.
In the meantime it can be done manually. I followed the suggestion in 0.0.7.
However I didn't have twine so needed to install.
If you need to do this then install via pip as apt-get gives you a version that is too old.
You may also need to install python 3 setuptools.
Once the package is created (see 0.0.7 release issue) the magic line is then ...
twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
I needed to provide the url explicitly.

**Comment by rupertford** [comment]
read the docs has updated
github has created a new release distribution
the new release is on pypi.
Closing issue.
