### ISSUE TITLE
fparser2 fails when parsing openmpi include files

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#139]
If we have some free format Fortran that contains:

    include 'mpif.h'

the fparser fails. I've reduced this down so that the included file only need be:

    ! -*- fortran -*-
          logical MPI_ASYNC_PROTECTS_NONBLOCKING
          ! Hard-coded for .false. for now
          parameter (MPI_ASYNC_PROTECTS_NONBLOCKING = .false.)

the first line causes the parser to identify the file as being "strict fixed format" and it then falls over when it finds the free-format comment. If I replace the first line with an empty comment then fparser identifies the file as "non-strict fixed format" and thus copes when it comes across the second comment.

So, should we use the format identified for the first file for all subsequent source files or do we need to do something else? We could make the check on the format of the file more robust for instance.

**Comment by arporter** [comment]
`get_source_info` has:

    firstline = lines[0].lstrip()
    if _HAS_F_HEADER(firstline):
        return FortranFormat(False, True)

where:

    _HAS_F_HEADER = re.compile(r'-[*]-\s*(fortran|f77)\s*-[*]-', re.I).search

and so it identifies the openmpi header as being strict fixed format. The Fortran standard says that the specification of whether source is fixed- or free-format is processor dependent.

I think the simplest fix is simply to change the mode it sets in this case as being non-strict.

**Comment by arporter** [comment]
Although my simple fix above gets me quite a long way, fparser still falls over on the very last OpenMPI include file. I've narrowed this down to the fact that we have an include file that contains an interface block. If the self same interface block is in-lined directly into the code then fparser is happy. However, if it is in an include file it raises a FortranSyntaxError:

    module include_test

      include 'my-include.h'

    !!$      INTERFACE MPI_Sizeof
    !!$
    !!$      SUBROUTINE simple()
    !!$      END SUBROUTINE simple
    !!$
    !!$      END INTERFACE MPI_Sizeof

    end module include_test

where my-include.h contains just:

    INTERFACE MPI_Sizeof

    SUBROUTINE simple()

    END SUBROUTINE simple

    END INTERFACE MPI_Sizeof

Note that on my `nemo_derisk` branch I've added the `-I` flag to PSyclone to specify directories in which to look for include files. However, I think it searches in the current working directory by default.

**Comment by rupertford** [comment]
I'll take this on.

The include support in the reader class seems to be a bit flaky so I'll use this issue to make it more robust including fixing the problem identified above.

**Comment by rupertford** [comment]
Created branch robust_include

**Comment by rupertford** [comment]
I've just tested the above code and it works in the current version of fparser so I'm closing this issue.
