### ISSUE TITLE
Supporting syntax extension to parse pointer statement

### ISSUE THREAD

**Issue by grnydawn** [stfc/fparser#143]
This might not be a parser bug, but Intel, PGI, and GNU(with -fcray-pointer) Fortran compilers support following pointer statement syntax extension using parentheses.

subroutine geopk16(...)
...      
      real (r8) inbuf8(1), outbuf8(1)
      pointer (ptr_inbuf8, inbuf8)  <== failed with FortranSyntaxError exception
      integer (i8) locinbuf, locoutbuf
...
end subroutine

**Comment by rupertford** [comment]
I can confirm that this format works with gfortran using the -fcray-pointer flag and that it fails with fparser2 ...

```
xed67771@arcgdel01:~/proj/fparser/src/fparser$ cat tmp.f90
subroutine geopk16()
real inbuf8(1), outbuf8(1)
pointer (ptr_inbuf8, inbuf8)
integer locinbuf, locoutbuf
end subroutine
xed67771@arcgdel01:~/proj/fparser/src/fparser$ gfortran -c tmp.f90
tmp.f90:3:8:

 pointer (ptr_inbuf8, inbuf8)
        1
Error: Cray pointer declaration at (1) requires -fcray-pointer flag
xed67771@arcgdel01:~/proj/fparser/src/fparser$ gfortran -c tmp.f90 -fcray-pointer
xed67771@arcgdel01:~/proj/fparser/src/fparser$ scripts/fparser2.py tmp.f90
Syntax error: at line 3
>>>pointer (ptr_inbuf8, inbuf8)

parsing 'tmp.f90' failed at line #3'pointer (ptr_inbuf8, inbuf8)'
started at line #1'subroutine geopk16()'
```

**Comment by rupertford** [comment]
Created pr #159

**Comment by arporter** [comment]
#159 is now merged. Closing issue.
