### ISSUE TITLE
Supporting syntax extension to parse format statement

### ISSUE THREAD

**Issue by grnydawn** [stfc/fparser#146]
This might not be a parser bug, but major Fortran compilers support a "char-string-edit-desc" that does not have quotation marks.

For example,

100 FORMAT(1X,29HGHP7 NOT CONVERGING FOR PRESS, 1PE12.2,E12.2)

fails with FortranSyntaxError exception on fparser2.

**Comment by rupertford** [comment]
Hi @grnydawn , this is not to do with quotation marks, or lack thereof.

H is a format specifier that was allegedly deleted in Fortran95. Quoting from here ... https://www.obliquity.com/computer/fortran/format.html

```
Another method is to use a Hollerith string. Named in honour of Herman Hollerith, an American inventer who founded a company that later became part of IBM, the H descriptor has the form nHstring where string is exactly n characters long.

The Hollerith string is a deprecated feature in FORTRAN 77 and its use is strongly discouraged.
```

So even back in Fortran77 days it was deprecated!

I can add it as an extension seeing as gfortran still deals with it.

**Comment by rupertford** [comment]
Created branch format-hollerith-string

**Comment by rupertford** [comment]
Associated pr is #160

**Comment by pelson** [comment]
@rupertford - can this issue now be closed?

**Comment by rupertford** [comment]
Yes, it should have been. Thanks @pelson.
