### ISSUE TITLE
Create defined operator class for rule R311.

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#157]
The Defined_Operator class is specified in Fortran2003.py but is not implemented. It is associated with Fortran 2003 rule 311. This issue will check whether it is required and, if it is, will implement it based on what was done in pr #142.

**Comment by rupertford** [comment]
The only place the the Defined_Operator rule is used is in rule R1207 where it is used as OPERATOR ( defined_operator ). An example of this use is ...

```
   interface operator (.avg.)
    function ComputeAvg(x, y)
      real, INTENT(IN) :: x
      real, INTENT(IN) :: y
      real :: ComputeAvg
    end function 
   end interface
```

**Comment by rupertford** [comment]
Created branch add_defined_operator

**Comment by arporter** [comment]
#158 has been merged to master. Closing Issue.
