### ISSUE TITLE
scripts/read.py contains Python-3 specific code

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#162]
As reported by Youngsung, installing fparser under Python 2 reports an error:

    Extracting fparser-0.0.8-py2.7.egg to /gpfs/u/home/youngsun/.local/lib/python2.7/site-packages
    File "/gpfs/u/home/youngsun/.local/lib/python2.7/site-packages/fparser-0.0.8-py2.7.egg/fparser
    /scripts/read.py", line 82
    print(item, file=sys.stdout)
                    ^
    SyntaxError: invalid syntax

This is because `read.py` is missing a `from future import print_function`.

**Comment by rupertford** [comment]
Created branch py3_fix.
Fixed the error and updated the file to conform to pycodestyle and pylint.

**Comment by arporter** [comment]
PR #185 is merged to master.
