### ISSUE TITLE
fparser2 should provide a list of Fortran Intrinsics

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#189]
PSyclone's NEMO API requires that we recognised/distinguish calls to Fortran intrinsics from array accesses. This functionality should really be a part of the parser.

**Comment by pelson** [comment]
I suspect to solve "distinguish calls to Fortran intrinsics from array accesses" *properly*, quite a bit of work needs to happen as I believe you need full context of what has already been defined/included/used (#190) (reminder: I'm still a novice with Fortran, and could very easily be wrong).

In #191 I've proposed a Parser class to hold state of the available parse elements. It would make a lot of sense to hold information about available intrinsics in the Parser instance, and for this information to be publicly available from the parser.

**Comment by rupertford** [comment]
Created branch 189_intrinsics

**Comment by arporter** [comment]
This functionality is now on master. Closing issue.
