### ISSUE TITLE
Wrong min. no. of args for SELECTED_REAL_KIND intrinsic.

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#204]
According to: https://gcc.gnu.org/onlinedocs/gcc-4.2.4/gfortran/SELECTED_005fREAL_005fKIND.html, the SELECTED_REAL_KIND intrinsic must have at least one argument but it is listed in `Fortran2003.py` as having a minimum of zero arguments.

**Comment by rupertford** [comment]
Yes, that is my mistake. The rule in the 2003 spec is
```
SELECTED REAL KIND ([P, R])
```
i.e. both P and R are optional, so I assumed 0 -> 2 args.

However the description in section 13.7.106 specifies that at least one of P or R must be present so it should be 1 -> 2.

**Comment by rupertford** [comment]
Created branch 204_selected_real_kind

**Comment by arporter** [comment]
#205 has been merged. Closing issue.
