### ISSUE TITLE
fparser2 fails (in Python2) when statements contain UTF characters

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#207]
Although we have previously added support to the reading/writing routines to cope with UTF characters, fparser2 still refuses to parse code if it contains UTF characters in actual statements (as opposed to comments). Although this is not valid Fortran most compilers cope with it and therefore so should fparser2. The error produced is:

    DEBUG    fparser.common.readfortran:readfortran.py:800 'ascii' codec can't encode character u'\xb2' in position 2: ordinal not in range(128)
    CRITICAL fparser.common.readfortran:readfortran.py:801 STOPPED READING

This same case works fine when running under Python 3.

**Comment by arporter** [comment]
Hi @rupertford, do you want to look at this or shall I continue with it?

**Comment by rupertford** [comment]
> Hi @rupertford, do you want to look at this or shall I continue with it?

If you are happy to continue then I'm happy! If you have more pressing things to do then I can pick it up. Is this something in NEMO?

**Comment by arporter** [comment]
Yes. I've only hit this because my PR for fixing this in PSyclone suddenly started failing when I updated it to HEAD of master. I think I've got it done now (all for the sake of the ~6 months that Python 2 has left).

**Comment by rupertford** [comment]
#208 is now on master so closing this issue.
