### ISSUE TITLE
fparser 0.0.9 release

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#216]
We are making a new release of PSyclone and that makes use of fparser2 features that are not yet in a release. Therefore I am making a new release of fparser2.

**Comment by mlange05** [comment]
@rupertford Would this be a good opportunity to update the version handling (issue #80) through something like the [Versioneer](https://github.com/warner/python-versioneer)? I think this would make also the version detection via pip a bit more robust. (Just my two cents, feel free to ignore.)

**Comment by rupertford** [comment]
Thanks @mlange05. Yes, it would have been but I've already pushed the new tag so it's too late. In theory travis is now creating the new release. However, as always seems to happen in fparser it fails for me with an issue with the password and @arporter needs to rerun to get it uploaded to pypi.

I forgot to mention Versioneer at our last PSyclone telco but will do at the next one.

**Comment by arporter** [comment]
I've done it manually following the instructions at https://packaging.python.org/tutorials/packaging-projects/. @rupertford please could you create an account on PyPi (if you don't already have one) and I'll add you as a maintainer - that will increase our bus factor :-)

**Comment by arporter** [comment]
You'll need to update the PSyclone setup.py to specify 0.0.9 of fparser.

**Comment by rupertford** [comment]
> I've done it manually following the instructions at https://packaging.python.org/tutorials/packaging-projects/. @rupertford please could you create an account on PyPi (if you don't already have one) and I'll add you as a maintainer - that will increase our bus factor :-)

YHPM

**Comment by rupertford** [comment]
github has created a new release, Andy has pushed the new version to pypi. However the stable version of fparser on read the docs has not yet updated. I'm keeping this issue open until this is done.

**Comment by rupertford** [comment]
@arporter. Could you manually push to read the docs as well? stable does not seem to have updated (but latest has).

**Comment by rupertford** [comment]
@arporter has updated rtd. Closing this issue.
