### ISSUE TITLE
de-parse of CASE block containing non-ascii char fails under Python 2

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#226]
Again, the non-ASCII char is in a string:

         CASE(  30  )       !==  fixed 3D shape  ==!
            IF(lwp) WRITE(numout,*) '   ==>>>   eddy viscosity = F( latitude, longitude, depth )'
            IF(lwp) WRITE(numout,*) '           maximum reachable coefficient (at the Equator) = ', zah_max, cl_Units, '  for e1=1°)'

**Comment by arporter** [comment]
This case fails at line 5571 of Fortran2003.py:

    def tofortran(self, tab='', isfix=None):
        tmp = []
        start = self.content[0]
        end = self.content[-1]
        tmp.append(start.tofortran(tab=tab, isfix=isfix))
        for item in self.content[1:-1]:
            if isinstance(item, Case_Stmt):
                tmp.append(item.tofortran(tab=tab, isfix=isfix))
            else:
                tmp.append(item.tofortran(tab=tab + '  ', isfix=isfix))
        tmp.append(end.tofortran(tab=tab, isfix=isfix))
        return '\n'.join(tmp)

**Comment by arporter** [comment]
This is similar to the problem fixed in #217

**Comment by arporter** [comment]
`BlockBase.tofortran()` has the same problem where it does a `"\n".join(tmp)`.

**Comment by arporter** [comment]
Strangely, I can only reproduce these errors in a pytest test when I use the `FortranFileReader` with `ignore_comments=False`. If I set it to `True` then all is fine.

**Comment by arporter** [comment]
With comments, the list of strings being `join`ed contains some (the comments) that are unicode while the code itself is just `str`. Without comments, the list of things being `join`ed does *not* contain any unicode strings and thus (presumably) no conversion is attempted.

**Comment by arporter** [comment]
The original problem is exercised if there is a comment *inside" a select case block. The problem in BlockBase is exercised if there is a comment just in the program body. I've added two tests to illustrate these.

**Comment by arporter** [comment]
I started down the road of making sure everything was unicode but that got rapidly out of hand and, theoretically, Python 2 end-of-life is only a month away. I've therefore gone for the minimal fix of ensuring that all strings are consistently encoded before we do a `join` on them (when producing Fortran).

**Comment by rupertford** [comment]
PR #227 has been merged to master. Closing this issue.
