### ISSUE TITLE
Fail gracefully when a line cannot be parsed

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#24]
When fparser encounters invalid Fortran it tends to fall over:

    File "somke_path/fparser/base_classes.py", line 647, in tofortran
    l.append(c.tofortran(isfix=isfix))
    AttributeError: 'Line' object has no attribute 'tofortran'

It would be much more helpful if it reported the location and content of the line where it had failed.
This can simply be done by putting the attempt to call `tofortran` within a try block, e.g. within `base_classes.BeginStatement.tofortran()`:

            for c in self.content:
            try:
                l.append(c.tofortran(isfix=isfix))
            except AttributeError:
                _, exc_value, _ = sys.exc_info()
                raise SomeError("Failed to parse {0}".format(str(c)))

**Comment by rupertford** [comment]
Parse error information is being introduced into fparser2. Closing this issue.
