### ISSUE TITLE
Virtual method `Select.get_classes()` should return NotImplementedError

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#25]
`block_statements.Select` is a base class, used by `SelectCase` and `SelectType`. The latter two classes both have a `get_classes` method but the base class does not. This means that if a user mistakenly creates a `Select` object then we will subsequently get attribute errors because it does not have a `get_class` method. We can improve on this by adding such a method to the base class and having it raise an error.

**Comment by rupertford** [comment]
fparser1 is no longer in development. Closing this issue.
