### ISSUE TITLE
fparser incorrectly adds KIND to class when generating Fortran

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#27]
Was ticket 595 on SRS. The description on that ticket is:

The following piece of code

{{{
function get_div(self) result(div)
  class(runtime_constants_type), target :: self
end function get_div
}}}

is output incorrectly in the current version of the parser

{{{
  FUNCTION get_div(self) RESULT ( div )
    CLASS(KIND=runtime_constants_type), target :: self
  END FUNCTION get_div
}}}

with the CLASS haveing a KIND parameter added. The following python can be used to demonstrate this problem.

{{{
from fparser import api as fpapi
filename = *****
ast = fpapi.parse(filename, analyze=False)
print ast
}}}

This problem needs fixing as the Met Office want to use this form of code in the algorithm layer.

**Comment by arporter** [comment]
Created class_kind_bug branch for this work.

**Comment by rupertford** [comment]
Pull request #28 has been merged to master. Closing this issue.
