### ISSUE TITLE
*_Expr classes do not check datatype

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#284]
The following rules have associated constraints

```
R724 logical-expr is expr
C705 (R724) logical-expr shall be of type logical.
R725 char-expr is expr
C706 (R725) char-expr shall be of type character.
R726 default-char-expr is expr
C707 (R726) default-char-expr shall be of type default character.
R727 int-expr is expr
C708 (R727) int-expr shall be of type integer.
R728 numeric-expr is expr
C709 (R728) numeric-expr shall be of type integer, real, or complex.
```

For example, a logical expression should be of type logical.

At the moment none of these constraints are enforced. Therefore an int-expr is simply matched as a general expression.

Whilst it is difficult to check that an expression is of a particular datatype in the general case there are certain cases where it is simple to know e.g. if the value is a Literal constant.

In this situation checks should be added.

One example where this causes an incorrect match is where a structure constructor with scalar and character values is incorrectly matched as an array access (designator).

**Comment by rupertford** [comment]
Created branch [284_expr_check_datatype](https://github.com/stfc/fparser/tree/284_expr_check_datatype)

**Comment by arporter** [comment]
#286 is merged.
