### ISSUE TITLE
Properly fix false matching in an exponent in Fortran 2003 R706 level-2-expr

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#290]
Fortran 2003 rule R706 matches a "+" or a "-" in an expression:

```
R706 level-2-expr is [ [ level-2-expr ] add-op ] add-operand
```

The problem with this matching is that an incoming string to match may have a "+" or a "-" as part of the exponent of a real literal. For example:

a - 1.0e-2

This can cause the implementation of the rule to falsely match.

The current solution is to

1) implement a special case when the real literal is on the RHS of the string which causes the rule to match with the next "+" or "-" to the left of the first

and

2) Modify the R705 add-operand rule to allow it to match with a level-2-expr a second time.

This is required for examples like the following:

a + 1.0e-2 * b

Together these solutions (hacks) fix the problem (or at least there are no cases where they don't).

However, a much nicer solution would be to make sure the level-2-expr rule did not falsely match in the first place.

The simplest solution would be to try to match each "+", or "-" until there was a successful match, or there were no more "+" or "-" in the string. However this would increase the parsing time (although perhaps not by much).

The proposed solution for this is to test whether a matched "+" or "-" is part of a real literal and ignore it if so.

If we incorrectly split a string into a lhs and rhs e.g.

string = "a + 1.0e-2 * b"
lhs = "a + 1.0e"
op = "-"
rhs = "2 * b"

we could then look at rhs to confirm that it has one or more digits followed by something that is not a digit

and at the lhs to confirm that it is the start of a real literal. The full rules need to be worked out but if we reverse the lhs string

lhs_reverse = "e0.1 + a"

we can see that we should have one of [eEdD] followed by [0-9]*[.]{0,1}[0-9]* with at least either one digit or a dot.

Potential pitfalls are a variable e.g. "a0e" which would mean an additional test for non-letters after the final digit.

However, it seems likely that a robust solution is feasible.

**Comment by arporter** [comment]
I think #302 has fixed this now or do you want to keep it open @rupertford ?

**Comment by rupertford** [comment]
Agreed. Closing.
