### ISSUE TITLE
Strict matching against Fortran intrinsics causes false Syntax Errors

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#291]
It is quite common for Fortran code to override existing Fortran intrinsics. e.g. one of NEMO's obs routines has an array named `IDIM` and NEMOVAR explicitly re-implements `dot_product`. Although this is perhaps not good practise, it is something we have to be able to cope with. Currently fparser2 has no type information and always assumes that if it finds an access of an array that happens to have the same name as an intrinsic then it *is* a call to that intrinsic. If the match to that intrinsic then fails (e.g. because the overridden routine has a different interface to that of the intrinsic) then fparser2 raises a Syntax Error. A better alternative would be to move on and attempt to match an array access instead.

**Comment by arporter** [comment]
There is an alternative solution which fits better with the plan to one day have type information and that is to allow some form of configuration that permits a user to specify that certain intrinsics have been overridden. (We could also use this approach to solve the statement-function problem.)

**Comment by rupertford** [comment]
> There is an alternative solution which fits better with the plan to one day have type information and that is to allow some form of configuration that permits a user to specify that certain intrinsics have been overridden. (We could also use this approach to solve the statement-function problem.)

Agreed. I think step 1 is to use symbol tables to find out what we can, then step 2, in the cases where we still don't know, we should be able to report on these when parsing the code and finally step 3, have the ability to read additional information via some form of configuration to resolve any unknowns (which would essential be the equivalent of a module file).

**Comment by arporter** [comment]
Having looked at #201 I see that I have effectively duplicated it here (I even mention the `idim` problem and @reuterbal mentions the `dot_product`). Therefore I'm closing this issue.
