### ISSUE TITLE
Add support for (Fortran2003) Procedure declarations

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#31]
fparser1 does not recognise procedure declarations such as:

     procedure(write_interface), pointer  :: tmp_ptr

In this issue we will add support for this (Fortran2003) feature.

**Comment by arporter** [comment]
Have begun to add a new, `Procedure` class to `fparser.typedecl_statements`. Is currently interpreting the `procedure_interface` as a KIND parameter which is obviously incorrect.

**Comment by arporter** [comment]
While doing this I've discovered that fparser already has `statements.SpecificBinding`. I think the only reason that this doesn't work for the case described in this issue is the `pointer` attribute. So, I think I can undo everything I've done so far and alter the `SpecificBinding` class instead.

**Comment by arporter** [comment]
I've added to the tests for `SpecificBinding` and it does in fact work OK for the example given in the intro to this issue. I therefore suspect that the problem is that this is a statement object and not a type declaration.

**Comment by arporter** [comment]
Added a new functional test that demonstrates the problem. The output of fparser for this test is helpful:

   23:    procedure (a) :: tmp_ptr <== no parse pattern found for "procedure (a) :: tmp_ptr" in 'Subroutine' block.

which implies that the fact the statement occurs in a "'Subroutine' block" is significant.

**Comment by arporter** [comment]
It is. The list of classes recognised as valid children of a given class is set-up at the end of `block_statements.py`. I can add `SpecificBinding` to the appropriate list and my new functional test passes. Strictly speaking, this is all that is required. However, in the Fortran code we're dealing with here we have a Procedure declaration which is not the same as a type- or object-bound procedure (although syntactically it is the same). Since it is syntactically the same, it doesn't seem right to effectively re-implement `SpecificBinding`. I therefore think my solution is OK although I will explicitly comment where I add `SpecificBinding` as being a valid declaration.

**Comment by rupertford** [comment]
Adding @svadams as a participant

**Comment by rupertford** [comment]
merged pr #32 to master. Closing issue.
