### ISSUE TITLE
fparser2: parse/generate INQUIRE calls

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#35]
When fparser2 parsers and then attempts to re-generate the following line:

    INQUIRE( unit = get_unit, opened = llopn )

it actually produces:

    INQUIRE(UNIT = get_unit, UNIT = opened = llopn)

which is invalid.

**Comment by arporter** [comment]
Created new `inquire_fix` branch for this work and extended existing test to cover all possible elements of the inquire-list. This now fails.

**Comment by rupertford** [comment]
pr #39 is now on master. Closing this issue.
