### ISSUE TITLE
restructure fparser2 tests

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#38]
fparser2 should have its own directory and the tests split into different files. Andy and I differ on how many files to split into at the moment but any modularity improvement would be good.

**Comment by MatthewHambley** [comment]
Has there been any consensus regarding how this split is to be achieved? It would be nice to be clear which code is the original fparser, which is the new one and which is shared. Then the tests can be split up, as suggested by this ticket.

**Comment by MatthewHambley** [comment]
I've had a crack at splitting the old and new parsers. See 10cb38a05b227f9edce28e1af35cd5089f8105bc

This is probably not functional although it does pass the unit tests for me. I have tried to maintain the existing API as it is exposed by api.py.

**Comment by rupertford** [comment]
@MatthewHambley kindly split fparser2 into its own directory and all new/updated fparser2 tests are being added in separate files. Closing this issue.
