### ISSUE TITLE
Support for `module procedure ::`

### ISSUE THREAD

**Issue by TeranIvy** [stfc/fparser#405]
`fparser2` raises a syntax error for `module procedure` statement when it is followed by double colon (`::`), e.g.

```
INTERFACE get_free_unit
MODULE PROCEDURE :: get_free_unit_32, get_free_unit_64
END INTERFACE get_free_unit
```
(see the relevant [LFRic source](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/lfricinputs/source/common/lfricinp_unit_handler_mod.f90?rev=42225#L16)).

When the double colon is omitted (e.g. `MODULE PROCEDURE get_free_unit_32, get_free_unit_64`), everything is fine. Both expressions pass compilation, so they should both be valid.

**Comment by rupertford** [comment]
The 2003 spec does not allow this:
`R1206 procedure-stmt is [ MODULE ] PROCEDURE procedure-name-list`
but the 2008 spec does:
`R1206 procedure-stmt is [ MODULE ] PROCEDURE [ :: ] procedure-name-list`

**Comment by rupertford** [comment]
So we need to add support for this as a F2008 extension. I'll remove the bug label :-).

**Comment by arporter** [comment]
@TeranIvy this is now on master. Please could you check that it resolves the Stylist problem and then I'll close this issue (and make a new release).

**Comment by rupertford** [comment]
This is now on master and has been checked with stylist.
