### ISSUE TITLE
Why is there an __init__.py in / and /src?

### ISSUE THREAD

**Issue by p-vitt** [stfc/fparser#41]
I just wanted to run the tests via nose, but weren't able to do so. Turns out that nose stumbles upon [/__init__.py](https://github.com/stfc/fparser/blob/master/__init__.py) and [/src/__init__.py](https://github.com/stfc/fparser/blob/master/src/__init__.py), which makes these folders a package, even though the real package should be below /src/fparser. Is there a reason for these two __init__.py files being where they are?

**Comment by arporter** [comment]
Yes, there is - I made a mistake :-)
I've created a `rm_surplus_inits` branch on which to fix this...

**Comment by arporter** [comment]
You beat me to it :-) Closing issue now PR is merged.
