### ISSUE TITLE
Add support for the open convert specifier (which is not part of the standard)

### ISSUE THREAD

**Issue by sergisiso** [stfc/fparser#426]
fparser fails to parse:
```
       open(unit       = MyUnit,       &
            file       = trim(filename), &
            form       = 'UNFORMATTED',  &
            access     = 'SEQUENTIAL',   &
            action     = 'WRITE',        &
            convert    = 'BIG_ENDIAN',   &
            iostat     = E_IO)
```

I believe this is because the "convert" is not part of the Fortran standard but it is supported by gfortran, nvfortran and ifort
https://gcc.gnu.org/onlinedocs/gfortran/CONVERT-specifier.html

**Comment by arporter** [comment]
WaveWatchIII also uses this and I've come to the same conclusion as @sergisiso - it's a common extension to the standard. Our default tactic is to support such things.
