### ISSUE TITLE
Compatibility with python3

### ISSUE THREAD

**Issue by p-vitt** [stfc/fparser#43]
I'm running into some issues when running fparser with python3. Is there anything planned on supporting python3? If not, are there any objections against making fparser compatible?

**Comment by arporter** [comment]
Ultimately, yes, we would like to move to python3 but we've not got the time at the moment. It would be brilliant if you could take this on.

**Comment by p-vitt** [comment]
I started with porting fparser to python3. Most of the stuff was done by 2to3. Unfortunately, not all unit tests pass afterwards. It seems that there is an issue with special dimension notations as well as with unordered lists. But for these problems I need to get a deeper understanding of how fparser works. I'm on it...

**Comment by arporter** [comment]
Great stuff. If I can help then do feel free to ask although my understanding of how fparser works isn't very deep as yet...

**Comment by rupertford** [comment]
Ditto for me.

**Comment by p-vitt** [comment]
First one found. In Python2 it is:
    
    >>> int('-11')
    -11
    >>> int('- 11')
    -11

whereas in Python3:

    >>> int('-11')
    -11
    >>> int('- 11')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: invalid literal for int() with base 10: '- 11'

This causes problems when e.g. the array dimension is specified like `integer :: a(- 5:5)`. A quick fix would be to change [line 256 in base_classes.py](https://github.com/stfc/fparser/blob/3cc5c52f00654edb58b6a7f8bfba6e7225818045/src/fparser/base_classes.py#L256) from

    dims = [tuple(dim.split(':')) for dim in dims]

to

    dims = [tuple(dim.replace(' ', '').split(':')) for dim in dims]

This way we could also leave the next line out, which only calls `str.strip()` on all elements in `dims`.

However, I'm not sure whether this is good coding practice in python as well as I'm not sure whether this introduces some side effects. Thus, I'll look for some manuals covering this change from py2 to py3 to get some more insights and possibly an advice on how to solve those incompatibilities.

**Comment by p-vitt** [comment]
According to the answers to my [question on stackoverflow](https://stackoverflow.com/questions/46787648/parsing-int-from-string-with-whitespace-differs-from-py2-to-py3), the Python2 behavior was a bug rather than an feature. So removing the blank characters seems to be the correct way. 

However, looking at the Fortran Standard (e.g. the [F2008 draft](http://j3-fortran.org/doc/year/10/10-007r1.pdf)), I'm not sure where to remove them. The F2008 Draft says on [page 47](http://j3-fortran.org/doc/year/10/10-007r1.pdf#page=65):

> Except in a character context, blanks are insignificant and may be used freely throughout the program.

This only counts for fixed form. For free form it says:

> In free source form blank characters shall not appear within lexical tokens other than in a character context or in a format specification.  Blanks may be inserted freely between tokens to improve readability; for example, blanks may occur between the tokens that form a complex literal constant.  A sequence of blank characters outside of a character context is equivalent to a single blank character.

Further ([p. 42](http://j3-fortran.org/doc/year/10/10-007r1.pdf#page=60)):

> A lexical token is a keyword, name, literal constant other than a complex literal constant, operator, statement label, delimiter, comma, =, =>, :, ::, ; or %.

A literal constant is ([p. 43](http://j3-fortran.org/doc/year/10/10-007r1.pdf#page=61)):

> R305 literal-constant is int-literal-constant [...]

which is ([p. 53](http://j3-fortran.org/doc/year/10/10-007r1.pdf#page=71)):

> Any integer value may be represented as a signed-int-literal-constant. 
R406 signed-int-literal-constant is [ sign ] int-literal-constant

I'm not sure if it is a good idea to remove the blank characters from the integer literal, as they seem to be formally wrong. Thus, failing instead of ignoring seems to be more appropriate. Which leads to the next problem: When it fails in this case, shouldn't it also fail in other cases?

**Comment by arporter** [comment]
Hmm. I've just tried with gfortran, PGI and Intel and they are all happy about (multiple) spaces between the sign and the integer. Of course, that doesn't mean that it's valid Fortran though!

**Comment by p-vitt** [comment]
Taking one step back, I think this isn't that much of a problem.

What is happening:

> ______________________________ test_dimension_attr _____________________________
>
>     def test_dimension_attr():
>         source_str = '''
>         subroutine foo
>         integer, dimension( -10 : 10, -   2147483648 : 2147483648) :: a( -2 : 2, 1000000 : 1000001 )
>         real, dimension(-20:20, 100:113, -  512  : 713) :: b
>         end
>         '''
>
>         tree = api.parse(source_str, isfree=True, isstrict=False)
>         subr = tree.a.external_subprogram['foo']
>         avar = subr.a.variables['a']
>
>         assert avar.dimension == [('-10', '10'), ('-   2147483648', '2147483648')]
>         assert avar.bounds == [('-2', '2'), ('1000000', '1000001')]
>         assert avar.shape == ['4', '1']
>
>         bvar = subr.a.variables['b']
>
>         assert bvar.dimension == [('-20', '20'), ('100', '113'), ('-  512', '713')]
>         print(("bvar.shape is {}".format(bvar.shape)))
>         assert bvar.shape == ['40', '13', '1225']
>     E       AssertionError: assert ['40', '13', '(713)-(-  512)'] == ['40', '13', '1225']
>     E         At index 2 diff: '(713)-(-  512)' != '1225'
>     E         Full diff:
>     E         - ['40', '13', '(713)-(-  512)']
>     E         + ['40', '13', '1225']
>
> fparser/tests/test_api.py:99: AssertionError
>------------------------------ Captured stdout call ------------------------------
> WARNING: While processing 'string-4373559696' (mode='free')..
>    1:
>    2:    subroutine foo
>    3:    integer, dimension( -10 : 10, -   2147483648 : 2147483648) :: a( -2 : 2, 1000000 : 1000001 ) <== both bounds=[('-2', '2'), ('1000000', '1000001')] and dimension=[('-10', '10'), ('-   2147483648', '2147483648')] are defined, ignoring dimension.
>    4:    real, dimension(-20:20, 100:113, -  512  : 713) :: b
>    5:    end
> WARNING: While processing 'string-4373559696' (mode='free')..
>    1:
>    2:    subroutine foo
>    3:    integer, dimension( -10 : 10, -   2147483648 : 2147483648) :: a( -2 : 2, 1000000 : 1000001 ) <== both bounds=[('-2', '2'), ('1000000', '1000001')] and dimension=[('-10', '10'), ('-   2147483648', '2147483648')] are defined, ignoring dimension.
>    4:    real, dimension(-20:20, 100:113, -  512  : 713) :: b
>    5:    end
> bvar.shape is ['40', '13', '(713)-(-  512)']

What do we see:

1. fparser successfully parses the testcase.
2. The unit test wants to check the array shape and therefore tries to interpret the array bounds.
3. The array bounds are not as expected (`'(713)-(-  512)'` instead of `'1225'`)
4. The bounds are incorrect (an array `a(-20:20)` has a shape of 41, not 40).

What is the conclusion? We either drop the flawed interpretation of fortran code or we fix it. As I currently don't know whether the unit tests are the only purpose for interpreting the code, I also can't decide on that one. But I'll try to find out whether this is only for testing purposes...

Besides that: We had a deep discussion about the Fortran standard. But, to be honest, it is not very accurate on that topic. It says _In free source form blank characters shall not appear within lexical tokens other than in a character context or in a format specification._ This means that it is basically allowed for blank characters to appear within lexical tokens. However, at least gfortran complains about `integer :: i = 1 000` with _Error: Syntax error in data declaration_, whereas `integer :: i = -  1` is not a problem. We also discussed whether a sign is a unary add operator or not. Here, again, the standard is not accurate. But, long story short, I think this discussion is not of interest for this problem, as this _seems_ to be a pure python unit test issue.

**Comment by p-vitt** [comment]
Seems to be finished. All unit tests pass, but there are still some minor things to do.

**Comment by p-vitt** [comment]
Actually, I didn't spent much thought about how to manage those changes I'm currently doing. Additionally, I don't use github that often, especially when it comes to branching and merging.
Right now I push everything into a branch on my fork of this repo. Is this how it should be?

**Comment by arporter** [comment]
Hello, yes, that is the right thing to do. We do a code review for each pull request following the guidelines [here](https://github.com/stfc/fparser/wiki/CodeReview). At the moment this can be quite painful since we're retrospectively applying these standards to a code base that was developed without them. The rule is that if a developer touches a routine while doing an Issue then it becomes the developer's responsibility to ensure that that routine is compliant. If you can create a Pull Request for what you've done then we can see how much you've had to change and whether we will have to rethink this rule for such a potentially wide-ranging Issue :-) You can continue to work on code after making a pull request - just tag the commits with the PR number.

**Comment by p-vitt** [comment]
Another question: What is the supposed outcome? Support for Python3 only? Or should I aim to stay compatible to Python2.7 as well as Python3?

**Comment by arporter** [comment]
Oh yes, we should have discussed that! We will need to keep compatibility with 2.7 as well. We can configure Travis to test with multiple Python versions by adding them below the ' - 2.7' entry in `.travis.yml`.

**Comment by arporter** [comment]
PR #48 has been merged. I just need to update the CHANGELOG now which I'll do on master.

**Comment by arporter** [comment]
CHANGELOG.md all up-to-date. Closing issue.
