### ISSUE TITLE
fparser does not accept all 'module procedure' declarations

### ISSUE THREAD

**Issue by hiker** [stfc/fparser#45]
According to the latest Fortran Standard draft (http://isotc.iso.org/livelink/livelink/19089292/N2137.pdf.flv?func=sspndocuments.Fetch&nodeid=19089292&viewType=1) R1506 the rule for a module procedure is:
```
R1506 procedure-stmt is [ MODULE ] PROCEDURE [ :: ] specific-procedure-list
```

Fparser does not accept the '::'.

Consider this assigned to me, patch is coming ;)

**Comment by rupertford** [comment]
Great, thanks!

**Comment by hiker** [comment]
Gee, at what time are you still working ;)

**Comment by rupertford** [comment]
I'm just an auto-respond bot set up by Rupert to make it look like he is working late.

**Comment by hiker** [comment]
See pull request.

Oh, is the auto-respond bot on github? I'd like a copy :)
