### ISSUE TITLE
fparser fails to reject type qualifiers on double precision and double complex variables

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#57]
Joerg has discovered that fparser will happily parse Fortran like:

    double precision*4 :: my_variable
    double complex*4 :: my_complex_variable

when in fact, any sort of KIND qualifier on those types is not permitted in the standard.

**Comment by hiker** [comment]
Similar to #52 - I am happy to make a correct Fortran code a prerequisite.

**Comment by rupertford** [comment]
fparser1 is no longer being supported and fparser2 raises a syntax error. Therefore I'm closing this issue.
