### ISSUE TITLE
Unexpected dependency on Numpy

### ISSUE THREAD

**Issue by MatthewHambley** [stfc/fparser#58]
I notice that fparser is dependent on Numpy. This seems a bit odd and potentially undesirable.

Using a simple "grep -r numpy ." I have identified two usage cases.

readfortran.py, base_classes.py and parsefortran.py all use it in order to print colour to the terminal. I don't know if this mechanism is portable but it is certainly a heavy weight dependency for such minor functionality.

utils.py make use of the function "numpy.ubyte" which seems to be an equivalent to C's "unsigned char". I'm not sure how necessary this is.

**Comment by arporter** [comment]
I agree (especially after just having had to wait a very long time to get numpy installed on a rather aged pi). The `ubyte` thing is used in the implementation of various `get_bit_size()` routines. However, grep'ing indicates that that routine is never actually used and this is borne out by the test coverage which shows that the bodies of the various `get_bit_size()` routines are not touched.

As for colour, I used `termcolor` in PSyclone so we could use that here as well (if we really care about coloured output).

Therefore, I think we could, with a little bit of work, remove the dependence on numpy.

**Comment by hiker** [comment]
I had a look at that as well. There is one additional dependency: setup.py uses numpy's Configuration class. I have no idea if this is necessary, and how to replace it.
And I would get rid of coloured output - fparser is a tool to be used by other programs, so it should just return messages some other way (exception, or perhaps via a log object to be supplied by the caller or ...)

**Comment by MatthewHambley** [comment]
I've had a look at the setup.py issue mentioned. The "configuration" function within, which uses numpy, loads the "log.config" file and uses it's contents to create an object. However a bit of grep work suggests that the function is never called. Further more "__init__.py" loads the same file into a standard Python "logging" object. So I suspect this numpy stuff can be safely removed as well.

**Comment by hiker** [comment]
That would be great news. I suspected that it might be part of the installation process (so might be called from the installer or so) ... but no idea. Yes, please let's get rid of that :)

**Comment by MatthewHambley** [comment]
It occurs to me that for the same reason that a library shouldn't be writing to terminal, it probably shouldn't be writing to a log file either. But That would be a second issue.

**Comment by MatthewHambley** [comment]
It looks like arporter was correct and `get_bit_size` is not used.

I should have a branch which removes the Numpy dependency in a day or so.

**Comment by arporter** [comment]
#62 has been merged to master. Closing this issue.
