### ISSUE TITLE
Should fparser be writing to a log file?

### ISSUE THREAD

**Issue by MatthewHambley** [stfc/fparser#59]
Given that fparser is a support library its current behaviour of writing to a log file seems wrong. Generally speaking libraries would be expected to raise an exception of return an error code for any error conditions. This leaves the calling program to decide how it wants to handle the problem.

However fparser potentially sends a lot of "warning" and even "info" level chatter to a log file although in normal operation all you get is:

> DEBUG: Not implemented: Defined_Binary_Op
> DEBUG: Not implemented: Defined_Binary_Op
> DEBUG: Defined_Operator not defined used by Generic_Spec

So there are two questions here: Do we want fparser writing to a log file at all? And if not, what to do about the less than fatal chatter it currently generates. There is potentially useful stuff there.

**Comment by rupertford** [comment]
I'm not even a novice on the use of logging and libraries but it seems to me that logging is a good thing in general whether the code is a library or not. What is required is the ability to manipulate what happens to the logging from the code that calls the library. I have read up a little on Python's logging API in the past and I believe it is designed to be used when different libraries are joined together and are called from other code so I would humbly suggest that we don't throw it away if it provides, Or could potentially provide, useful information.

Having said that I've never been able to control the logging properly from the parent Python script (for fparser) but I presume that is just my lack of understanding!

**Comment by hiker** [comment]
I would agree that fparser should not write to a file, but it should or course supply a logging mechanism that can be used by the caller. Then the caller can decide (either by parameters to fparser or a separate logging instance) what to do with messages.

E.g. a gui might want to parse the information and display the messages for the user.

**Comment by MatthewHambley** [comment]
To summarise, I think we agree that fparser shouldn't log specifically to a file but it should log events and leave it to the calling application to decide what to do with them.

From what I have read about the Python logging library the problem @rupertford  is seeing may be down to how fparse instantiates a logger. It does it at the head of each module. The problem here is that this is before any logging configuration has been enacted.

It seems that recommended practice is to only get a logger instance when you need to log, e.g.:

 > `logging.getLogger(__name__).info( 'Some message' )`

Note that the use of `__name__` which ensures uniqueness, assuming your packages are unique. It also means that the logging automatically follows any renames.

I have also seen a recommendation for inserting the following in your `__init__.py` file:

 > `import logging`
 > `logging.getLogger(__name__).addHandler(logging.NullHandler())`

This seems to be at odds with the first piece of advice as it is at module level.

**Comment by arporter** [comment]
I too share Rupert's (in)experience with logging. However, I do know that fparser currently configures its logging with the following code in `__init__.py`:

    # Default logging configuration file
    _DEFAULT_LOG_CONFIG_PATH = os.path.join(os.path.dirname(__file__),
                                            'log.config')
    # Setup loggers
    logging.config.fileConfig(_DEFAULT_LOG_CONFIG_PATH)

which doesn't seem very nice. This seems to be precisely the kind of thing that should be controlled by the calling application. The question then is what type of logging should fparser do out of the box? As a user I would only expect to get lots of non-fatal chatter if I requested 'verbose' output, and then probably on stdout.

**Comment by MatthewHambley** [comment]
Yes, that would seem like the least surprising behaviour. I think it is also the default of the logging library.

**Comment by arporter** [comment]
#65 is now on master. Closing issue.
