### ISSUE TITLE
Create a first release and upload to pypi

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#6]
Once ticket #1 has been merged to master we can create a first release.

**Comment by arporter** [comment]
#1 is done and the one failing test has been fixed.

**Comment by arporter** [comment]
Have uploaded version 0.0.1 to pypi.org. For the record, I did:
`python setup.py sdist` to build the source distribution
`python setup.py register -r pypi` to register the package with PyPi
`python setup.py sdist upload -r pypi` to actually upload the package.
I configured the test and real servers in my `~/.pypirc` file like so:
```
[distutils]
index-servers =
    pypi
    test

[test]
repository: https://testpypi.python.org/pypi
username: xxxxx
password: zzzz

[pypi]
repository: https://pypi.python.org/pypi
username: yyyy
password: xxxx
```
