### ISSUE TITLE
Fix failing test for entry construct

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#7]
In the initial import of fparser used to create this project, there is one failing test relating to an 'entry' construct. This has already been fixed in the version of fparser used by Habakkuk and that two-character change will be made in this issue.

**Comment by arporter** [comment]
Fix from Habakkuk (https://github.com/arporter/habakkuk/commit/b8fa1b979e4d7919c8596f6986d83de6e12022fe) applied. This was a 2-character fix that removes the requirement for a word boundary at the end of the matched string.

Will create a pull-request.

**Comment by rupertford** [comment]
Pull request #8 has been merged to trunk. The test no longer fails. In fact all tests pass. Closing ticket.
