### ISSUE TITLE
undefined variable "l" in block_statements.py inside HasImplicitStmt

### ISSUE THREAD

**Issue by sonofeft** [stfc/fparser#81]
Three places in def get_type_by_name use the undefined variable "l" 

Results in error:
  File "...\block_statements.py", line 115, in get_type_by_name
    t = implicit_rules.get(l, None)
NameError: global name 'l' is not defined

**Comment by arporter** [comment]
I can fix this quite simply but writing a test is proving tricky. Could you provide details/code of how you came across this bug in the first place?

**Comment by TeranIvy** [comment]
PR #88 merged to master so closed the issue.
