### ISSUE TITLE
restructure Fortran2003.py?

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#92]
fparser2 is mostly written in a single file which is unwieldy. It might be beneficial to split it into the different sections (rules) defined in the Fortran specification document and a generic file. This might cause a large number of files so needs some thinking about before implementation.

**Comment by rupertford** [comment]
Andy and I have been discussing how to restructure fparser2 to allow us to extend it to new fortran features. The restructuring will split the Fortran2003.py file so it makes sense to do this work as part of this issue.

What we would like to do is have a Fortran2008.py file which extends the Fortran2003.py file with any additional language features. In the longer term we could split Fortran2003.py into Fortran95.py and Fortran2003.py and work our way back to Fortran90.py via Fortran95.py. However, that would be future work.

At the moment there are 3 main sections in the Fortran2003.py file. 1) the classes defining the language, 2) a pre-processing section which generates additional classes from the existing classes and 3) a pre-processing section which populates the base class with all of the language objects and their relationships with other objects. This information is used when creating new objects.

It makes sense for parts one and two to stay together

If we want to support a Fortran2003 compliant compiler and a Fortran2008 compliant compiler we need to be able to populate the base class with the appropriate objects i.e. if we want Fortran2003 we use the classes from the Fortran2003.py file and create objects from them but if we want Fortran2008 we again use the classes from the Fortran2003.py file but replace ones that have been modified in the Fortran2008 file.

Therefore we propose to split part 3 of the Fortran2003.py file into its own file and create a factory method which creates the appropriate parser given a particular standard to conform to.

**Comment by rupertford** [comment]
Created branch restructure_test

**Comment by arporter** [comment]
Branch has been merged to master.
