### ISSUE TITLE
Code improvements for test_Fparser2003.py

### ISSUE THREAD

**Issue by TeranIvy** [stfc/fparser#95]
Since there is serious intention to move to fparser2, including PR #94 and issue #91, I thought of taking a part of code improvements tasks. This issue focuses on two things in `test_Fparser2003.py`:
- Replace `assert_equal` with `assert`,
- Rename invalid variable `a` to improve `pylint` score.

**Comment by arporter** [comment]
PR #96 has been merged. Closing issue.
