### ISSUE TITLE
fparser2 errors

### ISSUE THREAD

**Issue by rupertford** [stfc/fparser#99]
master now returns a line number and the line of code if there is a syntax error. However ...

1) there is a bug such that no error is returned when there are multiple program units and there is an error in a program unit other than the first one.

2) The error returned should be a SyntaxError rather than a NoMatchError.

3) Any fatal internal errors should return an InternalError

4) arguments (in particular the standard being used) should return an exception rather than exiting.

5) Any information output to do with decisions the parser is making should use a logger

**Comment by rupertford** [comment]
Created fparser2_error_handling branch

**Comment by arporter** [comment]
PR #100 has now been merged to master. Closing issue.
